# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "dev_el7_48_1" do |ovs1|
    ovs1.vm.box = "bento/centos-7.1"
    ovs1.vm.provision :shell, path: "bootstrap_gen.sh", args:"3.10.0-229.48.1"
    ovs1.vm.network "public_network"

    ovs1.vm.provider :virtualbox do |vb|
     vb.name = "dev_el7_48_1"
     vb.gui = true
     vb.customize ["modifyvm", :id, "--nictype1", "virtio" ]
     vb.customize ["modifyvm", :id, "--nictype2", "virtio" ]
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
     vb.customize ["modifyvm", :id, "--memory", "512"]
   end
  end
  config.vm.define "ovs_el7_48_1" do |ovs2|
    ovs2.vm.box = "bento/centos-7.1"
    ovs2.vm.provision :shell, path: "bootstrap_gen.sh", args:"3.10.0-229.48.1"
    ovs2.vm.network "public_network"

    ovs2.vm.provider :virtualbox do |vb|
     vb.name = "ovs_el7_48_1"
     vb.gui = true
     vb.customize ["modifyvm", :id, "--nictype1", "virtio" ]
     vb.customize ["modifyvm", :id, "--nictype2", "virtio" ]
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
     vb.customize ["modifyvm", :id, "--memory", "512"]
   end
  end
  config.vm.define "dev_el7_44_1" do |ovs3|
    ovs3.vm.box = "bento/centos-7.1"
    ovs3.vm.provision :shell, path: "bootstrap_gen.sh", args:"3.10.0-229.44.1"
    ovs3.vm.network "public_network"

    ovs3.vm.provider :virtualbox do |vb|
     vb.name = "dev_el7_44_1"
     vb.gui = true
     vb.customize ["modifyvm", :id, "--nictype1", "virtio" ]
     vb.customize ["modifyvm", :id, "--nictype2", "virtio" ]
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
     vb.customize ["modifyvm", :id, "--memory", "512"]
   end
  end

  config.vm.define "ovs_el7_44_1" do |ovs4|
    ovs4.vm.box = "bento/centos-7.1"
    ovs4.vm.provision :shell, path: "bootstrap_gen.sh", args:"3.10.0-229.44.1"
    ovs4.vm.network "public_network"

    ovs4.vm.provider :virtualbox do |vb|
     vb.name = "ovs_el7_44_1"
     vb.gui = true
     vb.customize ["modifyvm", :id, "--nictype1", "virtio" ]
     vb.customize ["modifyvm", :id, "--nictype2", "virtio" ]
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
     vb.customize ["modifyvm", :id, "--memory", "512"]
   end
 end

  end
